version: '3.1'

services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432