name: Library CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.java'
      - 'pom.xml'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.java'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: library.jar
        path: target/library-*.jar
        retention-days: 7
